version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    environment:
      NODE_ENV: production
    env_file:
      - ./.env
    ports:
      - 3012:3012
